from selenium import webdriver
import time

driver = webdriver.Chrome('/home/vamsi/Downloads/chromedriver')
driver.maximize_window()
driver.get('https://www.imdb.com/')
header_movies = driver.find_element_by_xpath('//*[@id="navTitleMenu"]/p/a[1]')
header_movies.click()
header_tv = driver.find_element_by_xpath('//*[@id="navTitleMenu"]/p/a[2]')
header_tv.click()
header_showtime = driver.find_element_by_xpath('//*[@id="navTitleMenu"]/p/a[3]')
header_showtime.click()
header_celebs = driver.find_element_by_xpath('//*[@id="navNameMenu"]/p/a[1]')
header_celebs.click()
header_events = driver.find_element_by_xpath('//*[@id="navNameMenu"]/p/a[2]')
header_events.click()
header_photos = driver.find_element_by_xpath('//*[@id="navNameMenu"]/p/a[3]')
header_photos.click()
header_news = driver.find_element_by_xpath('//*[@id="navNewsMenu"]/p/a[1]')
header_news.click()
header_community = driver.find_element_by_xpath('//*[@id="navNewsMenu"]/p/a[2]')
header_community.click()
# header_homebutton = driver.find_element_by_xpath('//*[@id="home_img"]')
# driver.click()
header_imdb_miniicon = driver.find_element_by_xpath('//*[@id="nav-mini-imdb"]')
header_imdb_miniicon.click()
# driver.execute_script("window.scrollBy(0,1000)","")
Marjavan = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-name-1"]') 
driver.execute_script("arguments[0].scrollIntoView();",Marjavan)
Marjavan.click()
Pagalpanti = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-name-2"]')
driver.execute_script("arguments[0].scrollIntoView();",Pagalpanti)
Pagalpanti.click()
Dabangg3 = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-3"]')
driver.execute_script("arguments[0].scrollIntoView();",Dabangg3)
Dabangg3.click()
Panipat = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-4"]')
driver.execute_script("arguments[0].scrollIntoView();",Panipat)
Panipat.click()
Mere_dad_ki_dulhan = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-5"]')
driver.execute_script("arguments[0].scrollIntoView();",Mere_dad_ki_dulhan)
Mere_dad_ki_dulhan.click()
Commando3 = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-6"]')
driver.execute_script("arguments[0].scrollIntoView();",Commando3)
Commando3.click()
# Mamangam = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-name-7"]/a')
# driver.execute_script("arguments[0].scrollIntoView();",Mamangam)
# Mamangam.click()
# Pati_Patni_Aur_Woh = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-name-8"]/a')
# driver.execute_script("arguments[0].scrollIntoView();",Pati_Patni_Aur_Woh)
# Pati_Patni_Aur_Woh.click()
# Motichoor_Chaknachoor = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-name-9"]/a')
# driver.execute_script("arguments[0].scrollIntoView();",Motichoor_Chaknachoor)
# Motichoor_Chaknachoor.click()
# Enai_Noki_Paayum_Thota = driver.find_element_by_xpath('//*[@id="trending-list-rank-item-name-10"]/a')
# driver.execute_script("arguments[0].scrollIntoView();",Enai_Noki_Paayum_Thota)
# Enai_Noki_Paayum_Thota.click()
Search_bar = driver.find_element_by_xpath('//*[@id="navbar-query"]')
driver.execute_script("arguments[0].scrollIntoView()",Search_bar)
Search_bar.click()
Search_bar.send_keys('Theri')
Search_icon = driver.find_element_by_xpath('//*[@id="navbar-submit-button"]/div')
Search_icon.click()
Theri = driver.find_element_by_xpath('//*[@id="main"]/div/div[2]/table/tbody/tr[1]/td[2]/a')
Theri.click()
Trending_Tamil_Movies = driver.find_element_by_xpath('//*[@id="main_bottom"]/div[2]/span/div/span/span/a/h3')
driver.execute_script("arguments[0].scrollIntoView()",Trending_Tamil_Movies)
Follow_IMDb_on = driver.find_element_by_xpath('//*[@id="footer"]/div[1]/div/div[2]/h3')
driver.execute_script("arguments[0].scrollIntoView()",Follow_IMDb_on)
driver.quit()
